// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	comment "demo/api_gateway/internal/handler/comment"
	user "demo/api_gateway/internal/handler/user"
	"demo/api_gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: user.LoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/demo"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/comment/action",
				Handler: comment.CommentActionHandler(serverCtx),
			},
		},
		rest.WithPrefix("/demo"),
	)
}
